In [43]:
import numpy as np

lst = [34, 56, 7]
arr = np.array (lst)
print (list(arr))

[np.int64(34), np.int64(56), np.int64(7)]


In [3]:
lst1 = [[2, 3], [3, 4]]
arr2d = np.array (lst1)
print (arr2d)

[[2 3]
 [3 4]]


In [4]:
print (list(arr))

[np.int64(34), np.int64(56), np.int64(7)]


In [7]:
arrz = np.ones ((3,3))
print (arrz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
rng = np.arange (2, 8, 3)
print (rng)

[2 5]


In [17]:
lnsp = np.linspace (0, 1, 5)
print (lnsp)

[0.   0.25 0.5  0.75 1.  ]


In [40]:
rand_arr = np.random.randint(1, 7, (3, 3))
print (rand_arr) 

[[2 6 6]
 [2 1 3]
 [4 2 2]]


In [50]:
ra = np.random.randint (1, 10, 6)
print (ra)
sra = ra[1:5]
print (sra)
rra = ra.reshape(3,2)
print (rra)
print (rra[1, :])

[5 9 8 2 9 3]
[9 8 2 9]
[[5 9]
 [8 2]
 [9 3]]
[8 2]
